name: AsyncAPI documents processing

on:
  push:
    branches:
      - "main"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-generator@v2.1.7
        with:
          template: "@asyncapi/html-template" #In case of template from npm, because of @ it must be in quotes
          filepath: services/recipe.yaml
          # parameters: baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
          output: recipe
